// Run with Playwright installed: node tests/browser.test.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const root = path.resolve(__dirname, '..');
assert.equal(fs.readFileSync(path.join(root, 'index_V6.html'), 'utf8'), fs.readFileSync(path.join(root, 'index.html'), 'utf8'), 'Default page and V6 must stay in sync');
const errors = [];
const server = http.createServer((req, res) => {
  const requestPath = req.url.split('?')[0];
  const file = /^\/assets\/brands\/(kb-logo\.png|sh-logo\.png|hd-logo\.svg)$/.test(requestPath) ? requestPath.slice(1) : requestPath === '/wallet-validation.js' ? 'wallet-validation.js' : requestPath === '/index_V6.html' ? 'index_V6.html' : 'index.html';
  res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript; charset=utf-8' : file.endsWith('.png') ? 'image/png' : file.endsWith('.svg') ? 'image/svg+xml' : 'text/html; charset=utf-8');
  res.end(fs.readFileSync(path.join(root, file)));
});
const visible = async (page, selector) => assert.equal(await page.locator(selector).isVisible(), true, selector);
const close = async page => { await page.keyboard.press('Escape'); };
async function swipe(page, selector, dir = 1, touch = false) {
  const rect = await page.locator(selector).boundingBox();
  const y = rect.y + Math.min(rect.height / 2, 120), x = rect.x + rect.width * (dir === 1 ? .8 : .2), end = x - dir * rect.width * .6;
  if (touch) {
    const session = await page.context().newCDPSession(page);
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] });
    for (let i = 1; i <= 6; i++) await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + (end - x) * i / 6, y }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await session.detach();
  } else {
    await page.mouse.move(x, y); await page.mouse.down(); await page.mouse.move(end, y, { steps: 8 }); await page.mouse.up();
  }
  // The app suppresses the click generated by a swipe for 400ms.
  await page.waitForTimeout(450);
}
async function add(page, name, number, type = 'membership') {
  await page.locator('.view:not([hidden]) [data-open="add"]').click();
  await page.locator(`#addSeg [data-v="${type}"]`).click();
  await page.locator('#addName').fill(name); await page.locator('#addCode').fill(number);
  await page.locator('#addForm [type="submit"]').click();
}
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}/`;
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  try {
    for (const width of [390, 320]) {
      const context = await browser.newContext({ viewport: { width, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce', colorScheme: 'dark' });
      const page = await context.newPage();
      page.on('pageerror', e => errors.push(e.message));
      await page.route('https://fonts.googleapis.com/**', route => route.abort());
      await page.goto(url);
      await visible(page, '#v-home');
      assert.equal(await page.locator('#heroTotal').innerText(), '203,500');
      assert.equal(await page.locator('#lgFee').innerText(), '40,700');
      assert.equal(await page.locator('#lgNet').innerText(), '162,800');
      assert.ok(await page.locator('.hero').evaluate(el => el.scrollWidth <= el.clientWidth));
      await page.waitForFunction(() => [...document.querySelectorAll('#homeCardRail img')].every(img => img.complete && img.naturalWidth > 0));
      await page.locator('[data-open="stmt"]').click();
      assert.equal(await page.locator('#stFee').innerText(), '40,700원');
      assert.equal(await page.locator('#stCoupon').innerText(), '−1,000원');
      assert.equal(await page.locator('#stFinal').innerText(), '39,700원'); await close(page);
      if (width === 390 && process.env.QA_OUTPUT) { fs.mkdirSync(process.env.QA_OUTPUT, { recursive: true }); await page.screenshot({ path: path.join(process.env.QA_OUTPUT, 'hero-demo-dark.png') }); }
      assert.ok(await page.locator('.tabbar').evaluate(el => parseFloat(getComputedStyle(el, '::before').transitionDuration) < .001));
      assert.equal(await page.locator('#homeCardRail .home-card').count(), 3);
      assert.equal(await page.locator('#homeMembers .home-member').count(), 3);
      assert.equal(await page.locator('#homeRate').innerText(), '80%');
      assert.equal(await page.locator('#homeMissed').innerText(), '19,600원');
      await page.locator('#homeCardRail .home-card').nth(1).click(); await visible(page, '#sh-code'); assert.match(await page.locator('#cdTitle').innerText(), /Mr.Life/); await close(page); await visible(page, '#v-home');
      await page.locator('#homeMembers [data-m="0"]').click(); await visible(page, '#sh-pass'); await close(page); await visible(page, '#v-home');
      await page.locator('#homeCategories [data-category="dine"]').click(); assert.match(await page.locator('#detailBody').innerText(), /111,000/); await close(page); await visible(page, '#v-home');
      await page.locator('#homeBest').click(); assert.match(await page.locator('#detailTitle').innerText(), /SKT/); await close(page);
      await page.locator('#demoCampusMap').scrollIntoViewIfNeeded(); await page.locator('#demoCampusMap [data-campus="0"] .map-pin').click(); assert.match(await page.locator('#detailBody').innerText(), /예시 안내 · 현장 검증 전/); await close(page);
      if (width === 390 && process.env.QA_OUTPUT) { fs.mkdirSync(process.env.QA_OUTPUT, { recursive: true }); await page.locator('.home-analysis').scrollIntoViewIfNeeded(); await page.screenshot({ path: path.join(process.env.QA_OUTPUT, 'home-analysis-dark.png') }); await page.locator('.home-wallet').scrollIntoViewIfNeeded(); await page.screenshot({ path: path.join(process.env.QA_OUTPUT, 'home-wallet-dark.png') }); }
      await page.locator('.detect-card h3').click();
      assert.equal(await page.locator('#flow').evaluate(el => el.classList.contains('on')), false);
      await page.locator('#btrack').scrollIntoViewIfNeeded(); await swipe(page, '#btrack', 1, true);
      assert.match(await page.locator('#bcount').innerText(), /2 \/ 3/); await visible(page, '#v-home');
      await page.locator('#v-home').evaluate(el => el.scrollTop = 0);
      await swipe(page, '.views', 1, true); await visible(page, '#v-history');
      await swipe(page, '#histList', 1, true); await visible(page, '#v-history');
      assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'done');
      assert.equal(await page.locator('#histList .tx').count(), 4);
      await swipe(page, '#chips', 1); assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'pending');
      await swipe(page, '#histList', 1, true); assert.equal(await page.locator('#histList .tx').count(), 1);
      assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'missed'); await visible(page, '#v-history');
      assert.equal(await page.locator('#histList .tx.open').count(), 0);
      await swipe(page, '#historySwipe', 1, true); await visible(page, '#v-stats');
      await page.locator('#cats [data-category="dine"]').click();
      assert.match(await page.locator('#detailBody').innerText(), /빕스.*|111,000/); await close(page);
      await page.locator('#rank [data-benefit="kb"]').click();
      assert.equal(await page.locator('#detailBody [data-transaction]').count(), 2);
      await page.locator('#detailBody [data-transaction]').first().click();
      assert.match(await page.locator('#detailBody').innerText(), /리캐치 성공 수수료/); await close(page);
      await page.locator('#v-stats [data-insight="success"]').click(); assert.match(await page.locator('#detailBody').innerText(), /완료 4건/); await close(page);
      await page.locator('#trend [data-month="0"]').click(); assert.match(await page.locator('#detailBody').innerText(), /개별 결제 데이터/); await close(page);
      await swipe(page, '.tabbar', 1); await visible(page, '#v-wallet');
      assert.equal(await page.locator('#cardMeta [data-card-saving]').innerText(), '86,000원');
      assert.equal(await page.locator('#cardMeta [data-card-fee]').innerText(), '17,200원');
      assert.equal(await page.locator('#cardMeta [data-card-net]').innerText(), '68,800원');
      await page.locator('#cardMeta [data-card-history="0"]').click();
      assert.equal(await page.locator('#detailBody [data-transaction]').count(), 2); await page.locator('#detailBody [data-transaction]').first().click();
      assert.match(await page.locator('#detailBody').innerText(), /수수료 20%: 5,200원/); await close(page);
      assert.equal(await page.locator('#memList .mem').count(), 3);
      assert.equal(await page.locator('#memMore').isVisible(), false);
      await page.locator('#memList [data-m="0"]').click(); await swipe(page, '#passRail', 1, true);
      assert.match(await page.locator('#passIdx').innerText(), /2 \/ 3/);
      await swipe(page, '#passRail', -1); assert.match(await page.locator('#passIdx').innerText(), /1 \/ 3/); await close(page);
      await page.locator('#facts [data-condition="student"]').click();
      assert.match(await page.locator('#conditionReason').innerText(), /예시 프로필/);
      await page.locator('#conditionValue').selectOption({ label: '대학원생' }); await page.locator('#conditionForm [type="submit"]').click();
      assert.match(await page.locator('#facts').innerText(), /대학원생/);
      await page.reload(); await visible(page, '#v-wallet'); assert.match(await page.locator('#facts').innerText(), /대학원생/);
      await page.locator('#facts [data-condition="region"]').click();
      await page.locator('#conditionValue').selectOption({ label: '기타 지역' }); await page.locator('#conditionCustom').fill('수원시');
      await page.locator('#conditionForm [type="submit"]').click(); assert.match(await page.locator('#facts').innerText(), /수원시/);
      await add(page, '테스트', ''); assert.match(await page.locator('#addError').innerText(), /입력/);
      await page.locator('#addCode').fill('12345678abc'); await page.locator('#addForm [type="submit"]').click(); assert.match(await page.locator('#addError').innerText(), /숫자만/);
      await page.locator('#addCode').fill('7700-1923-8832-1049'); await page.locator('#addForm [type="submit"]').click(); assert.match(await page.locator('#addError').innerText(), /이미 지갑/); await close(page);
      await add(page, '<img src=x onerror=alert(1)>', '1234 5678 9012');
      await page.waitForFunction(() => !document.querySelector('#sh-add').classList.contains('on'));
      assert.equal(await page.locator('#memList .mem').count(), 3); await visible(page, '#memMore');
      await page.locator('#memMore').click(); assert.equal(await page.locator('#collectionBody .mem').count(), 4);
      assert.equal(await page.locator('#collectionBody img').count(), 0);
      if (width === 390 && process.env.QA_OUTPUT) { fs.mkdirSync(process.env.QA_OUTPUT, { recursive: true }); await page.screenshot({ path: path.join(process.env.QA_OUTPUT, 'membership-all-dark.png') }); }
      await page.locator('#collectionBody [data-m="3"]').click(); assert.equal(await page.locator('#passRail .pass').count(), 4);
      assert.match(await page.locator('#passIdx').innerText(), /4 \/ 4/); await close(page);
      await add(page, '추가 카드', '2345678901234567', 'card');
      await page.waitForFunction(() => !document.querySelector('#sh-add').classList.contains('on'));
      assert.equal(await page.locator('#cardRail .ccard').count(), 3); await page.locator('#cardsMore').click();
      assert.equal(await page.locator('#collectionBody [data-card-detail]').count(), 4);
      await page.locator('#collectionBody [data-card-detail="3"]').click(); await page.locator('[data-card-code="3"]').click(); await visible(page, '#sh-code'); await close(page);
      // Server adapter: same normalized failed number is blocked without a second call, even after reload.
      await page.evaluate(() => { window.calls = 0; window.RecatchMembershipAPI = { validate: async () => { window.calls++; return { ok: false, code: 'NOT_FOUND' }; } }; });
      await add(page, '실패 번호', '345678901234'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('찾을 수'));
      await page.locator('#addCode').fill('3456-7890-1234'); await page.locator('#addForm [type="submit"]').click();
      await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('다시 요청하지'));
      assert.equal(await page.evaluate(() => window.calls), 1); await close(page);
      await page.reload(); await page.evaluate(() => { window.calls = 0; window.RecatchMembershipAPI = { validate: async () => { window.calls++; return { ok: true }; } }; });
      await add(page, '동일 실패 번호', '345678901234'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('다시 요청하지'));
      assert.equal(await page.evaluate(() => window.calls), 0); await close(page);
      await page.evaluate(() => { window.RecatchMembershipAPI = { validate: async () => { window.calls++; throw Error('network'); } }; });
      await add(page, '네트워크', '456789012345'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('연결 문제'));
      await page.locator('#addForm [type="submit"]').click(); await page.waitForFunction(() => window.calls === 2); await close(page);
      // Existing cards, membership rails and demo outcome paths remain usable.
      await page.locator('#cardRail').scrollIntoViewIfNeeded();
      await swipe(page, '#cardRail', 1, true); assert.match(await page.locator('#cardMeta').innerText(), /Mr.Life/); await visible(page, '#v-wallet');
      const before = await page.locator('#v-wallet').evaluate(el => el.scrollTop);
      const rect = await page.locator('.views').boundingBox(), touchSession = await context.newCDPSession(page);
      await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: width / 2, y: rect.y + 500 }] });
      for (let i = 1; i <= 6; i++) await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: width / 2, y: rect.y + 500 - i * 30 }] });
      await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await touchSession.detach();
      await page.waitForTimeout(100); assert.ok(await page.locator('#v-wallet').evaluate(el => el.scrollTop) > before); await visible(page, '#v-wallet');
      await page.locator('.tabbar [data-tab="home"]').click(); await page.locator('#simCard').click();
      await page.locator('#rcNoti').click(); await page.locator('#pyOk').click(); await page.locator('#dnOk').click();
      assert.equal(await page.locator('#heroCount').innerText(), '5');
      assert.equal(await page.locator('#homeAnalysisCount').innerText(), '완료 5건');
      await page.locator('#simCard').click(); await page.locator('#rcNoti').click(); await page.locator('#pySkip').click();
      await page.locator('.tabbar [data-tab="history"]').click(); await page.locator('#chips [data-f="missed"]').click(); assert.equal(await page.locator('#histList .tx').count(), 2);
      await page.locator('.tabbar [data-tab="wallet"]').click();
      if (width === 390) {
        const output = process.env.QA_OUTPUT;
        if (output) { fs.mkdirSync(output, { recursive: true }); await page.screenshot({ path: path.join(output, 'wallet-dark.png') }); }
      }
      assert.equal(await page.evaluate(() => document.querySelector('.app').scrollWidth <= document.querySelector('.app').clientWidth), true);
      await context.close();
      console.log(`PASS: ${width}px, touch/mouse gestures, details, overflow, validation/cache, conditions, demo regression`);
    }
    // Normal motion: the outgoing and incoming pages follow a drag, then settle.
    const animatedContext = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'no-preference', colorScheme: 'dark' });
    const animated = await animatedContext.newPage();
    animated.on('pageerror', e => errors.push(e.message));
    await animated.route('https://fonts.googleapis.com/**', route => route.abort());
    await animated.goto(`${url}index_V6.html`);
    const viewBox = await animated.locator('.views').boundingBox(), y = viewBox.y + 100;
    await animated.mouse.move(300, y); await animated.mouse.down(); await animated.mouse.move(220, y, { steps: 5 });
    const drag = await animated.evaluate(() => {
      const current = document.querySelector('#v-home'), next = document.querySelector('#v-history');
      return { currentX: new DOMMatrix(getComputedStyle(current).transform).m41, nextX: new DOMMatrix(getComputedStyle(next).transform).m41, preview: !next.hidden, inert: next.inert };
    });
    assert.ok(drag.currentX < 0 && drag.nextX > 0 && drag.preview && drag.inert);
    if (process.env.QA_OUTPUT) await animated.screenshot({ path: path.join(process.env.QA_OUTPUT, 'tabs-during-swipe.png') });
    await animated.mouse.up();
    await animated.waitForFunction(() => document.querySelector('#v-history').getAnimations().length > 0);
    assert.equal(await animated.locator('#v-home').getAttribute('aria-hidden'), 'true');
    await animated.waitForFunction(() => document.querySelectorAll('.view:not([hidden])').length === 1 && !document.querySelector('#v-history').hidden);
    assert.equal(await animated.locator('.tabbar').evaluate(el => el.style.getPropertyValue('--tab-index')), '1');
    // History rows and the filter strip switch only the small tabs, in both directions.
    for (const [filter, count] of [['done', 4], ['pending', 1], ['missed', 1]]) {
      await swipe(animated, '#histList', 1, true); await visible(animated, '#v-history');
      assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), filter);
      assert.equal(await animated.locator('#histList .tx').count(), count);
      assert.equal(await animated.locator('#histList .tx.open').count(), 0);
    }
    await swipe(animated, '#historySwipe', 1, true); await visible(animated, '#v-stats');
    await animated.locator('.tabbar [data-tab="history"]').click(); await animated.waitForTimeout(300);
    await swipe(animated, '#histList', -1); assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), 'pending'); await visible(animated, '#v-history');
    await swipe(animated, '#histList', -1, true); assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), 'done');
    await swipe(animated, '#histList', -1, true); assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), 'all');
    await swipe(animated, '#historySwipe', -1, true); await visible(animated, '#v-home');
    await animated.locator('.tabbar [data-tab="history"]').click(); await animated.waitForTimeout(300);
    const filterBox = await animated.locator('#chips').boundingBox(), filterY = filterBox.y + filterBox.height / 2;
    await animated.mouse.move(150, filterY); await animated.mouse.down(); await animated.mouse.move(116, filterY, { steps: 5 }); await animated.mouse.up(); await animated.waitForTimeout(450);
    assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), 'done'); await visible(animated, '#v-history');
    await animated.locator('#chips [data-f="all"]').click();
    await swipe(animated, '.tabbar', 1, true); await visible(animated, '#v-stats');
    await swipe(animated, '.views', 1, true); await visible(animated, '#v-wallet');
    await swipe(animated, '.tabbar', -1, true); await visible(animated, '#v-stats');
    await swipe(animated, '.views', -1); await visible(animated, '#v-history');
    await swipe(animated, '#chips', 1, true); assert.equal(await animated.locator('#chips .on').getAttribute('data-f'), 'done'); await visible(animated, '#v-history');
    // A short drag within one bottom-menu button is sufficient to switch pages.
    const tabBox = await animated.locator('.tabbar').boundingBox(), tabY = tabBox.y + tabBox.height / 2;
    await animated.mouse.move(150, tabY); await animated.mouse.down(); await animated.mouse.move(116, tabY, { steps: 5 }); await animated.mouse.up(); await animated.waitForTimeout(450);
    await visible(animated, '#v-stats');
    // A sub-threshold content drag bounces back, with no accidental tap/navigation.
    await animated.mouse.move(250, y); await animated.mouse.down(); await animated.mouse.move(225, y, { steps: 4 }); await animated.mouse.up(); await animated.waitForTimeout(450);
    await visible(animated, '#v-stats'); assert.equal(await animated.locator('.view:not([hidden])').count(), 1);
    assert.equal(await animated.locator('.sheet.on').count(), 0);
    await animated.locator('.tabbar [data-tab="home"]').click(); await animated.waitForTimeout(300);
    await swipe(animated, '.views', -1, true); await visible(animated, '#v-home'); assert.equal(await animated.locator('.view:not([hidden])').count(), 1);
    // Rapid tab selections cancel stale animation completions and leave one active page.
    await animated.locator('.tabbar [data-tab="wallet"]').click(); await animated.locator('.tabbar [data-tab="history"]').click(); await animated.locator('.tabbar [data-tab="stats"]').click();
    await animated.waitForTimeout(350); await visible(animated, '#v-stats'); assert.equal(await animated.locator('.view:not([hidden])').count(), 1);
    assert.equal(await animated.locator('.tab.on').getAttribute('data-tab'), 'stats');
    await animated.locator('.tabbar [data-tab="home"]').click(); await animated.waitForTimeout(300);
    await add(animated, '홈에서 추가한 멤버십', '567890123456');
    await animated.waitForFunction(() => !document.querySelector('#sh-add').classList.contains('on'));
    await visible(animated, '#v-home'); assert.equal(await animated.locator('#homeMembers .home-member').count(), 3);
    await animated.locator('#homeMembersMore').click(); assert.equal(await animated.locator('#collectionBody .mem').count(), 4);
    await animated.locator('#collectionBody [data-m="3"]').click(); assert.match(await animated.locator('#passRail').innerText(), /홈에서 추가한 멤버십/); await close(animated);
    await animatedContext.close();
    console.log('PASS: animated drag previews, both directions, all four pages, short menu swipe, bounce-back, boundaries, rapid navigation and home wallet refresh');
    // Empty filters retain a full-height gesture area, including blank space below the message.
    for (const width of [390, 320]) {
      const emptyContext = await browser.newContext({ viewport: { width, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce' });
      const empty = await emptyContext.newPage(); empty.on('pageerror', e => errors.push(e.message));
      await empty.route('https://fonts.googleapis.com/**', route => route.abort());
      await empty.route('**/?empty=1', route => route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(root, 'index.html'), 'utf8').replace(/let TX=\[[\s\S]*?\];/, 'let TX=[];') }));
      await empty.goto(`${url}?empty=1`); await empty.locator('.tabbar [data-tab="history"]').click();
      assert.equal(await empty.locator('#histList').innerText(), '아무것도 없어요');
      const area = await empty.locator('#historySwipe').boundingBox(), nav = await empty.locator('.tabbar').boundingBox();
      assert.ok(area.height >= 260 && area.y + area.height >= nav.y - 40);
      await swipe(empty, '#historySwipe', -1, true); await visible(empty, '#v-home');
      await empty.locator('.tabbar [data-tab="history"]').click();
      for (const filter of ['done', 'pending', 'missed']) { await swipe(empty, '#historySwipe', 1, true); assert.equal(await empty.locator('#chips .on').getAttribute('data-f'), filter); assert.equal(await empty.locator('#histList').innerText(), '아무것도 없어요'); }
      if (width === 390 && process.env.QA_OUTPUT) await empty.screenshot({ path: path.join(process.env.QA_OUTPUT, 'history-empty-area.png') });
      await swipe(empty, '#historySwipe', 1, true); await visible(empty, '#v-stats');
      await emptyContext.close();
    }
    console.log('PASS: empty and blank-space swipes, full-height area and home/analysis edge transitions at both mobile widths');
    // Very large demo totals still fit the receipt on a narrow screen.
    const large = await browser.newPage({ viewport: { width: 320, height: 844 }, reducedMotion: 'reduce' });
    large.on('pageerror', e => errors.push(e.message));
    await large.route('https://fonts.googleapis.com/**', route => route.abort());
    await large.route('**/?large=1', route => route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(root, 'index.html'), 'utf8').replace("cat:'cvs',amount:6500,save:650", "cat:'cvs',amount:987654320,save:98765432") }));
    await large.goto(`${url}?large=1`); await large.waitForTimeout(50);
    assert.equal(await large.locator('#homeCardRail .art-sh').evaluate(el => getComputedStyle(el).color), 'rgb(255, 255, 255)');
    assert.ok(await large.locator('.hero').evaluate(el => el.scrollWidth <= el.clientWidth));
    assert.ok(await large.locator('.hero-amt').evaluate(el => el.scrollWidth <= el.clientWidth));
    if (process.env.QA_OUTPUT) await large.screenshot({ path: path.join(process.env.QA_OUTPUT, 'hero-large-total.png') });
    await large.close();
    // Extra source categories and benefits keep the original 4/3 previews and expose all items.
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    page.on('pageerror', e => errors.push(e.message));
    await page.route('**/', route => route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(root, 'index.html'), 'utf8').replace("srcKey:'cj',status:'pending'", "srcKey:'cj',status:'done'").replace("id:6,store:'맘스터치 영남대점',cat:'dine'", "id:6,store:'맘스터치 영남대점',cat:'bake'").replace("srcKey:'skt',status:'missed'", "srcKey:'skt',status:'done'") }));
    await page.goto(url); await page.locator('.tabbar [data-tab="stats"]').click();
    assert.equal(await page.locator('#cats .cat').count(), 4); assert.equal(await page.locator('#rank .rank').count(), 3);
    await page.locator('#catsMore').click(); assert.equal(await page.locator('#collectionBody [data-category]').count(), 6); await close(page);
    await page.locator('#rankMore').click(); assert.equal(await page.locator('#collectionBody [data-benefit]').count(), 4); await close(page);
    const output = process.env.QA_OUTPUT;
    if (output) { await page.screenshot({ path: path.join(output, 'stats-light.png') }); await page.locator('#cats .cat').first().click(); await page.screenshot({ path: path.join(output, 'detail-light.png') }); }
    assert.deepEqual(errors, []);
    console.log('PASS: overflow fixtures and zero browser runtime errors');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
